# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require 'test-unit'

class Euler002Tests < Test::Unit::TestCase
  def test_002
    assert_equal([1, 2, 3, 5, 8, 13, 21, 34, 55, 89], fib(90))
  end
end

def fib limit
  [1, 2].tap do |arr|
    arr << arr.last(2).sum while arr.last <= limit
    arr.pop if arr.last > limit
  end
end

def problem_2
  p fib(4_000_000).select(&:even?).sum
end

problem_2
